version: '3'
services:
  app:
    container_name: game_character_app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - game_character-postgres          # Uncomment this when using postgres.
    networks:
      - game_character


  game_character-postgres:
    image: postgres:latest
    container_name: game_character_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5435:5435'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - game_character
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - game_character-postgres
    ports:
      - "5050:80"
    networks:
      - game_character
    restart: unless-stopped

volumes:
  api:
  database_postgres:                  # Uncomment this when using postgres.
 
# Networks to be created to facilitate communication between containers
networks:
  game_character:
    driver: bridge